name: Vote
main: Savion\Main
version: "1.0-BETA"
api: [1.12.0]
author: SavionLegendZzz
commands:
  vote:
    description: Vote yes or no!
    permission: vote.command.vote
    default: true
  newvote:
    description: Start a vote!
    permission: vote.command.newvote
    default: true
  yes:
    description: Vote yes!
    permission: vote.command.yes
    default: true
  no:
    description: Vote no!
    permission: vote.command.no
    default: true
