name: Vote
main: Savion\Main
version: "1.1_Beta"
api: [1.12.0]
load: POSTWORLD
author: SavionLegendZzz
commands:
 newvote:
  permission: vote.command.newvote
  description: Start a vote!
 vote:
  permission: vote.command.vote
  description: Vote yes or no!
